export const BODY_PART = [
  { value: 'upper_arms', label: 'Bracos (superiores)' },
  { value: 'lower_arms', label: 'Bracos (inferiores)' },
  { value: 'back', label: 'Costas' },
  { value: 'cardio', label: 'Cárdio' },
  { value: 'upper_legs', label: 'Pernas (superiores)' },
  { value: 'lower_legs', label: 'Pernas (inferiores)' },
  { value: 'chest', label: 'Peito' },
  { value: 'neck', label: 'Pescoco' },
  { value: 'waist', label: 'Quadril' },
  { value: 'shoulders', label: 'Ombros' },
]

export const EQUIPAMENT = [
  { label: "Peso do corpo", value: "body_weight" },
  { label: "Cabo", value: "cable" },
  { label: "Máquina de alavanca", value: "leverage_machine" },
  { label: "Assistido", value: "assisted" },
  { label: "Bola medicinal", value: "medicine_ball" },
  { label: "Bola de estabilidade", value: "stability_ball" },
  { label: "Banda elástica", value: "band" },
  { label: "Barra de levantamento", value: "barbell" },
  { label: "Corda", value: "rope" },
  { label: "Haltere", value: "dumbbell" },
  { label: "Barra ez", value: "ez_barbell" },
  { label: "Máquina de empurrar", value: "sled_machine" },
  { label: "Ergômetro superior", value: "upper_body_ergometer" },
  { label: "Haltere russo", value: "kettlebell" },
  { label: "Barra olímpica", value: "olympic_barbell" },
  { label: "Com peso", value: "weighted" },
  { label: "Bola bosu", value: "bosu_ball" },
  { label: "Banda de resistência", value: "resistance_band" },
  { label: "Rolo de espuma", value: "roller" },
  { label: "Máquina skierg", value: "skierg_machine" },
  { label: "Martelo", value: "hammer" },
  { label: "Máquina smith", value: "smith_machine" },
  { label: "Roda de abdominais", value: "wheel_roller" },
  { label: "Bicicleta estacionária", value: "stationary_bike" },
  { label: "Pneu", value: "tire" },
  { label: "Barra de armadilha", value: "trap_bar" },
  { label: "Máquina elíptica", value: "elliptical_machine" },
  { label: "Máquina stepmill", value: "stepmill_machine" }
];

export const TARGET = [
  { label: "Abdominais", value: "abs" },
  { label: "Quádriceps", value: "quads" },
  { label: "Dorsais", value: "lats" },
  { label: "Panturrilhas", value: "calves" },
  { label: "Peitorais", value: "pectorals" },
  { label: "Glúteos", value: "glutes" },
  { label: "Isquiotibiais", value: "hamstrings" },
  { label: "Adutores", value: "adductors" },
  { label: "Tríceps", value: "triceps" },
  { label: "Sistema Cardiovascular", value: "cardiovascular_system" },
  { label: "Coluna", value: "spine" },
  { label: "Dorsais Superiores", value: "upper_back" },
  { label: "Bíceps", value: "biceps" },
  { label: "Deltoides", value: "delts" },
  { label: "Antebraços", value: "forearms" },
  { label: "Trapezoides", value: "traps" },
  { label: "Serrátil Anterior", value: "serratus_anterior" },
  { label: "Abdutores", value: "abductors" },
  { label: "Elevador da Escápula", value: "levator_scapulae" }
]
