name: Vercel Develop Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - staging

jobs:
  Deploy-Development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}
      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=$(vercel env pull --environment=development --token=${{ secrets.VERCEL_TOKEN }} | grep NEXT_PUBLIC_SUPABASE_URL | cut -d' ' -f2)" > .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$(vercel env pull --environment=development --token=${{ secrets.VERCEL_TOKEN }} | grep NEXT_PUBLIC_SUPABASE_ANON_KEY | cut -d' ' -f2)" >> .env.local
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
